# Generated by Django 4.2.3 on 2023-08-13 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_orderbook_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderbooks', to='ecommerce.order'),
        ),
    ]
