# Generated by Django 4.2.3 on 2024-04-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_orderbook_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
