# Generated by Django 4.2.3 on 2023-07-31 10:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=6, max_length=6, prefix='', primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=10, null=True)),
                ('last_name', models.CharField(max_length=10, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('bio', models.TextField()),
                ('pic', models.ImageField(upload_to='book/author/%Y/%m/%d/')),
                ('website', models.URLField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=6, max_length=6, prefix='', primary_key=True, serialize=False, unique=True)),
                ('ISBN', models.CharField(max_length=13, null=True, unique=True)),
                ('title', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('reviews_count', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('publish_date', models.DateField(null=True)),
                ('num_pages', models.IntegerField(null=True)),
                ('cover_image', models.FileField(upload_to='book/cover_image/%Y/%m/%d/')),
                ('page_image', models.FileField(upload_to='book/page_image/%Y/%m/%d/')),
                ('condition', models.CharField(choices=[('New', 'New'), ('Old', 'Old')], max_length=20, null=True)),
                ('stock', models.CharField(choices=[('In Stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=6, max_length=6, prefix='', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('icon', models.ImageField(null=True, upload_to='book/category/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=6, max_length=6, prefix='', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('website', models.URLField(max_length=255, null=True)),
                ('social_twitter', models.URLField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=6, max_length=6, prefix='', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=6, max_length=6, prefix='', primary_key=True, serialize=False, unique=True)),
                ('rating_value', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('rating_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='book.book')),
            ],
        ),
    ]
