# Generated by Django 4.2.3 on 2023-08-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_review_options_remove_book_reviews_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_reviews',
        ),
    ]
