# Generated by Django 4.2.3 on 2023-08-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_review_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
