# Generated by Django 4.2.3 on 2023-08-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_book_bookprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
